services:

  # --- BASE DE DATOS (PostgreSQL) ---
  postgres:
    image: postgres:16-alpine
    container_name: sgv-postgres
    environment:
      POSTGRES_DB: sgv_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sgv_pgdata:/var/lib/postgresql/data
    networks:
      - sgv-network
    restart: unless-stopped

  # --- API .NET ---
  sgv-api:
    build:
      context: .
      dockerfile: SGV.API/Dockerfile
    container_name: sgv-api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=sgv_db;Username=postgres;Password=postgres
      - AllowedOrigins=http://localhost:4200
      - Jwt__Key=SuperSecretKeyParaSGV_Sistemas_9990234234_!
      - Jwt__Issuer=SGV_API
      - Jwt__Audience=SGV_Client
    depends_on:
      - postgres
    networks:
      - sgv-network
    restart: unless-stopped

  # --- FRONTEND ANGULAR ---
  sgv-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sgv-frontend
    ports:
      - "4200:80"
    depends_on:
      - sgv-api
    networks:
      - sgv-network
    restart: unless-stopped

networks:
  sgv-network:
    driver: bridge

volumes:
  sgv_pgdata:
    driver: local
